### PR TITLE
Code of conduct & freelancing illustrations

### PR DESCRIPTION
**Pull request by hlaposhka**

### CODE REVIEW

**Comment by IanMayo** [comment]
Note - I see layout issues like this in Chrome:
image

**Comment by IanMayo** [comment]
Thanks for the update :-)

I love the artwork.

Would you consider some _Easter eggs_ - just to show it's custom artwork and not clip-art?  We could hide a Deep Blue C shark logo in the images.  Obviously this means a change to the image, so I'm quite happy to pay for your time to do it.

**Comment by IanMayo** [comment]
(wow - that fix for the layout overlap was a lot of work!)

**Comment by hlaposhka** [comment]
Do you mean add to every picture? I'll see what i can do

**Comment by IanMayo** [comment]
Yes, that does seem a lot of work. But, hopefully each one won't take too much time.  Maybe create small shark logo in each of the blue shades - then just add one to each diagram.

Oh dear - I hope this isn't going to spoil them.

If you think it's a silly idea, please tell me :-)

**Review by IanMayo — APPROVED** [review]
Looking great, thanks :-)

**Pull request merged**
